# Generated by Django 4.1.2 on 2023-02-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='value',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Value'),
        ),
    ]
